### ISSUE TITLE
FIX: 게임페이지 툴팁 모달창 위치 수정하기

### ISSUE THREAD

**Issue by heayounchoi** [gachimind/frontend#43]
## 이슈 요약

화면 비율 조정 시 툴팁 모달창 위치가 이상한 관계로 뜯어 고칠 예정

<br>

## TODO

- [x] 툴팁 모달창 위치 조정하기
- [x] selection ref 속성 조정

**Comment by pds0309** [comment]
슬랙에 올려드린 Select 컴포넌트 클릭시 ref의 위치로 인해 useClickAway가 동작하는부분도 개선되면 좋을것 같습니다 😄
