### ISSUE TITLE
FEAT: 카메라/마이크 관련 편의기능 추가하기

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#80]
## 이슈 요약

사용자 카메라/마이크와 관련된 편의 기능을 추가한다.

<br>

## TODO

- 캠 로드 되고 있을 동안 로드 스피너 적용하기 `난이도: 상`
- 사용자 마이크 사용 시 캠 border 하이라이트 시키기 `난이도: 중`
- ~~마이크로 말한 사용자 캠 목록 맨앞으로 배치시키기~~ `난이도: 상`
- 캠 목록의 캠에 마우스 오버 시 확대 아이콘을 우측 상단에 보여주고 클릭 시 메인 캠에 확대시키기 및 되돌리기 기능 추가 `난이도: 상`

<br>

## 참고

- 시간이 나면 진행합니다.
- 계획에 없던 부가기능으로 밥 먹다가 생각난거 작성해둡니다
- @heayounchoi  ~~줄쳐져있는것~~은 검토해보시고 괜찮으면 이슈 수정하기에서 줄을 풀어주세요

아 그리고 캠 목록에 사용자가 3명 미만일 경우 원래 empty 캠을 넣어서 채워뒀었는데 최근에 지웠거든여 있는게 낫나요 없는게 낫나요?

**Comment by heayounchoi** [comment]
@pds0309 넵 없는게 나아용!!!

**Comment by heayounchoi** [comment]
@pds0309 마이크로 말한 사용자를 맨앞으로 끌고 오면 모든 사용자가 말할때마다 앞으로 오는건가여?? 그럼 정신 없을거같은뎀,,
