### ISSUE TITLE
TEST: 스토리북 세팅 및 CI 설정

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#84]
## 이슈 요약

스토리북 사용을 위해 세팅하라

<br>

## 왜 함?

**독립적인 컴포넌트 (특히 UI적인)를 구성하고자 할 때 구성 자체에 어려움이 있다.**

- 특히 게임 페이지 내부의 무언가를 만들고자 할 때는 변경이나 추가할 때 마다 게임페이지에 들어가 게임을 돌려봐야하는 어려움이 있다.
- 해당 컴포넌트의 수정/리팩터링에 대해서만 확인하며 개발하고 싶지만 어려움이 있다.

<br>

**독립적인 컴포넌트 추가/수정/리팩터링에 대해 코드 or 움짤로만 PR 리뷰를 파악해야한다.**

- PR시 배포자동화 해두고 리뷰어에게 스토리북 추가/변경 사항을 알려주어 빠르게 UI에 대해 확인할 수 있다.

<br>

**상호작용/이벤트가 많은 컴포넌트가 있다**

- 이걸 매번 실제 있어야 할 위치에 두면서 수정/추가 해나가며 확인하기에는 어려움이 있다.
- 독립적으로 잘 동작하는지 확인하며 개발한다.

<br>

## TODO

- 스토리북 세팅
- 스토리북 CI/CD 구성

<br>

## 하고싶은 말

- 정말 필요하다고 생각될 때만 사용하셔도 됩니다.(스토리북 작성 자체는 매우 간단합니다!)
- 크고 너무 복잡한 로직(리덕스 상태, 소켓)이 포함되어 있는 컴포넌트는 적용이 어렵습니다. 
- 작은 단위의 컴포넌트를 구성해나가면서 큰 페이지를 만드는 개발 방법(컴포넌트 주도 개발)에 적합한 테스팅 도구지만 있으면 좋을 것 같아서 적용하고자 합니다. 동의 시 따봉을 달아주세요!

**Comment by heayounchoi** [comment]
@pds0309 시간적 여유가 있나용??? 있다면 환영입니당 ㅎㅎㅎㅎ

**Comment by pds0309** [comment]
> @pds0309 시간적 여유가 있나용??? 있다면 환영입니당 ㅎㅎㅎㅎ

막 엄청 오래걸리지는 않습니다!
